[config]
schemaVersion = "0.0.1"

[package]
namespace = "ninesolsmodding"
name = "NineSolsAPI"
versionNumber = "1.2.3"
description = "Modding API for Nine Sols"
websiteUrl = "https://github.com/nine-sols-modding/NineSolsAPI"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
